### PR TITLE
Rebase - Adding tailwind

### PR DESCRIPTION
**Pull request by MatsJoh50**
Rebased previous PR. (hopefully it works)

Added tailwind to React Frontend with a Proof div in the test page from Vite to confirm that it works.

Issue #44

### CODE REVIEW

**Comment by kappsegla** [comment]
Which issue is this PR linked to?

**Review by sebastianpiresmolin — DISMISSED** [review]
I see that you had to rebase your commits due to issues with signing you commits right? Good work on getting it working with the gpg key!

**Comment by MikaelaMathisson** [comment]
Tailwind sounds great. The code looks good and looks clean to me. I think its also easy to read through the code. Great job on working with the gpg key 👍 :-)

**Review by MikaelaMathisson — DISMISSED** [review]
Approving!

**Comment by MatsJoh50** [comment]
> Which issue is this PR linked to?

Thank you, Issue created, #44

**Review by MikaelaMathisson — APPROVED** [review]
Approving again 👍

**Review by sebastianpiresmolin — APPROVED** [review]
Still looks good, the rebasing seems to be have gone through smoothly and should integrate smoothly.

**Pull request merged**
