### PR TITLE
73 create tests for graphql queries and custom exceptions

### PR DESCRIPTION
**Pull request by AlbinNils98**
### Overview: Integration Tests for User GraphQL Queries

This PR adds a set of integration tests for the `UserController` GraphQL API to ensure its functionality and robustness. The following scenarios are covered:

1. **Successful Retrieval of Users**: Verifies that the API returns a list of users when data is available.
2. **Resource Not Found Exception**: Ensures that when no users are found, a `ResourceNotFoundException` is returned with appropriate error details in the GraphQL response.
3. **Unexpected Exception Handling**: Tests the handling of unexpected runtime exceptions, confirming that an internal server error is returned with the correct error message and type.

The tests utilize `@GraphQlTest` to isolate the `UserController` and mock the service layer. Assertions are made to validate both the structure and content of the GraphQL responses, ensuring the API behaves as expected in various scenarios.

## Summary by CodeRabbit

- **New Features**
  - Introduced a framework for integration testing of GraphQL queries in the `UserController`.

- **Tests**
  - Added three integration tests to verify user retrieval and error responses in the `UserController`.
  - Established error handling tests for scenarios including resource not found and unexpected exceptions.

### CODE REVIEW

**Review by MikaelaMathisson — CHANGES_REQUESTED** [review]
I think the tests looks great and well structured. Its easy to follow and does what it should. 

I did notice that there are 3 issues from the sonarcloud that would be recommended to change to improve the maintainability. They are not necessary for the code to work but it looks like it would be easy and quick to fix 🥇

**Comment by AlbinNils98** [comment]
@MikaelaMathisson the Sonarcloud issues are now resolved!

**Review by MikaelaMathisson — APPROVED** [review]
> @MikaelaMathisson the Sonarcloud issues are now resolved!

Great! Approving

**Review by oskber — APPROVED** [review]
Good and well-structured tests for graphql 👍

**Review by rasmusbaeckstrom — APPROVED** [review]
This looks good Albin. Great work.

**Pull request merged**
