### PR TITLE
#19 Display List of Users 

### PR DESCRIPTION
**Pull request by MickeMarten**
This PR introduces a UsersPage component that fetches user data using a GraphQL query and displays it.
Created pages-folder for folder structure.

Notes:
To test the component locally, you'll need to add http://localhost:8080/graphql as a .env variable or just use the url in the fetch function, configure CORS settings on the backend by adding a CorsConfigurationSource bean and disabling CSRF.  
Replace the existing code and run "npm run dev" in frontend path and visit http://localhost:5173/users

**_### Do not use the example code for production nor merge it to main, it is for trying out this PR only. The cors issue will be resolved in issue #58_** 

Example code for SecurityConfig.java.

```
@Bean
@Profile("development")
public SecurityFilterChain developmentSecurityFilterChain(HttpSecurity http) throws Exception {
    http
        .cors(cors -> cors.configurationSource(corsConfigurationSource()))
        .csrf(AbstractHttpConfigurer::disable)
        .authorizeHttpRequests(auth -> auth
            .anyRequest().permitAll()
        )
        .httpBasic(Customizer.withDefaults());
    return http.build();
}

@Bean
public CorsConfigurationSource corsConfigurationSource() {
    CorsConfiguration configuration = new CorsConfiguration();
    configuration.setAllowedOrigins(Arrays.asList("http://localhost:5173"));
    configuration.setAllowedMethods(Arrays.asList("GET", "POST", "PUT", "DELETE"));
    configuration.setAllowedHeaders(Arrays.asList("Authorization", "Content-Type"));
    UrlBasedCorsConfigurationSource source = new UrlBasedCorsConfigurationSource();
    source.registerCorsConfiguration("/**", configuration);
    return source;
}

```
Skärmbild 2024-12-17 232612

## Summary by CodeRabbit

- **New Features**
	- Introduced a new `/users` route for navigating to the Users page.
	- Added a Users page that fetches and displays a list of users with their names and emails.

- **Bug Fixes**
	- Implemented error handling for user data fetching.

### CODE REVIEW

**Review by HannaRosberg — DISMISSED** [review]
The component effectively fetches and displays a list of users from a GraphQL endpoint. The use of useState and useEffect for managing state and side effects is appropriate and well-structured.

Loading and error states are managed effectively, providing appropriate feedback to the user.

The code is easy to follow, with descriptive variable names and clean JSX structure.

Suggestion for improvement😊:

The message "No one uses our application" could be rephrased to something more neutral or encouraging, like "No users found. Please check back later."

Extract the GraphQL query into a separate constant for better readability and maintainability.

const FETCH_USERS_QUERY = `
    {
        users {
            name
            email 
        }
    }
`;

**Comment by MickeMarten** [comment]
> The component effectively fetches and displays a list of users from a GraphQL endpoint. The use of useState and useEffect for managing state and side effects is appropriate and well-structured.
> 
> Loading and error states are managed effectively, providing appropriate feedback to the user.
> 
> The code is easy to follow, with descriptive variable names and clean JSX structure.
> 
> Suggestion for improvement😊:
> 
> The message "No one uses our application" could be rephrased to something more neutral or encouraging, like "No users found. Please check back later."
> 
> Extract the GraphQL query into a separate constant for better readability and maintainability.
> 
> const FETCH_USERS_QUERY = `{ users { name email } }`;

**Comment by MickeMarten** [comment]
> Extract the GraphQL query into a separate constant for better readability and maintainability.
> 
> const FETCH_USERS_QUERY = `{ users { name email } }`;

Great tip @HannaRosberg!

**Review by MikaelaMathisson — APPROVED** [review]
The code fetches and displays users, and does what it should. Its well structured and easy to read.

There is good feedback to the user, which is great.
The variable names are clean and easy to understand and makes the code easy to follow.

I saw the comments from Hanna about improving the feedback "No one uses our application" to something more natural and I agree with that comment.  Other than that I think the code looks good and can be merged.

**Comment by MickeMarten** [comment]
@MikaelaMathisson  @HannaRosberg  changes to the text is done =)

**Review by MikaelaMathisson — APPROVED** [review]
Nice work! Approving :)

**Review by HannaRosberg — APPROVED** [review]
Nice work with the changes. I'm approving too :)

**Pull request merged**
