### PR TITLE
#16 - Create react

### PR DESCRIPTION
**Pull request by MatsJoh50**
Added folder: Frontend

used Vite Create React app with TS as frontend.

added script: npm run start => start both SB and React (might need modification)
Added Proxy to frontend package.json to open the connection with BE. this will need a change since its localhost:8080 atm.

### CODE REVIEW

**Review by sebastianpiresmolin — DISMISSED** [review]
I see that you have brought in react using vite. That's great, we all have experience using vite. I also see that you have seperated the file structure between frontend and backend which I think is fitting! I would personally have named backend 'server' instead, or maybe just keep it as is and just have the frontend in a specific frontend directory. I see that the CI error you are getting is related to file naming or targeting? Approving this now so that its ready to merge when the CI is green.

**Comment by MatsJoh50** [comment]
> I see that you have brought in react using vite. That's great, we all have experience using vite. I also see that you have seperated the file structure between frontend and backend which I think is fitting! I would personally have named backend 'server' instead, or maybe just keep it as is and just have the frontend in a specific frontend directory. I see that the CI error you are getting is related to file naming or targeting? Approving this now so that its ready to merge when the CI is green.

Good input.
went back from Backend folder to springboot in root and kept Frontend folder.
this also fixes the CI problem.

**Review by oskber — DISMISSED** [review]
Looks good to me, I like the structure of springboot as root and a separate frontend folder.
The codereviewbot have some pointers that might be good to look into.

**Review by sebastianpiresmolin — DISMISSED** [review]
I see my approval went away witht he latest commit, re-approving!

**Review by sebastianpiresmolin — APPROVED** [review]
I see that you've rebased your commits to sign them. Great!

**Review by MikaelaMathisson — APPROVED** [review]
I think this PR looks great. It does what it should and the code is clean. Its easy to look through and understand. Great work :-) 💯

**Pull request merged**
